version: "2"
services:
    app:
        build: .
        stdin_open: true
        tty: true
        networks: 
            subnet:
                ipv4_address: 172.20.1.2

    db:
        image: postgres:11
        environment: 
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        stdin_open: false
        tty: false
        networks:
            subnet:
                ipv4_address: 172.20.1.3
        volumes:
            - db_volume:/var/lib/postgresql/data

volumes:
    db_volume:

networks:
    subnet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.1.0/24
                  gateway: 172.20.1.1
