version: "2"
services:
    app:
        build: .
        depends_on:
            - "db"
        stdin_open: true
        tty: true
        networks: 
            subnet:
                ipv4_address: 172.20.1.2
        volumes:
            - app_volume:/go

    db:
        image: postgres:11
        environment: 
            - "POSTGRES_PASSWORD=password"
        stdin_open: false
        tty: false
        networks:
            subnet:
                ipv4_address: 172.20.1.3
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d/
            - db_volume:/var/lib/postgresql/data

volumes:
    app_volume:
    db_volume:

networks:
    subnet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.1.0/24
                  gateway: 172.20.1.1
